USE master
GO

IF EXISTS(SELECT * FROM SysDataBases WHERE NAME = 'DailyGoals')
	BEGIN
		DROP DATABASE DailyGoals
	END
GO

CREATE DATABASE DailyGoals
GO

USE DailyGoals
GO

CREATE TABLE USERS
(
	USER_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	USER_NAME VARCHAR(20) NOT NULL,
	USER_MAIL VARCHAR(50) NOT NULL,
	USER_EXPERIENCE INT NOT NULL
)
GO

CREATE TABLE DAILYGOAL
(
	DAILY_GOAL_ID UNIQUEIDENTIFIER DEFAULT NEWID() UNIQUE,
	USER_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES USERS(USER_ID),
	GOAL_DATE DATETIME,
	EMOTION INT,
	PRIMARY KEY(DAILY_GOAL_ID, USER_ID)
)
GO

CREATE TABLE GOAL (
	GOAL_ID INT NOT NULL,
	GOAL_TEXT VARCHAR(50) NOT NULL,
	DAILY_GOAL_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES DAILYGOAL(DAILY_GOAL_ID),
	PRIMARY KEY(GOAL_ID, DAILY_GOAL_ID)
)
GO

CREATE TABLE COMMENT
(
	COMMENT_ID UNIQUEIDENTIFIER DEFAULT NEWID() UNIQUE NOT NULL,
	USER_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES USERS(USER_ID),
	COMMENT_MAIN VARCHAR(1000),
	COMMENT_DATE DATETIME,
	COMMENT_EMOTION INT
)
GO


-------------------------
-- STANDARD PROCEDURES --
-------------------------

-------------------------
--- CREATE PROCEDURES ---
-------------------------

CREATE PROCEDURE CREATE_USER
@USER_NAME VARCHAR(20),
@USER_MAIL VARCHAR(50)
AS
	BEGIN
		INSERT USERS VALUES(NEWID(), @USER_NAME, @USER_MAIL, 1)
		IF @@ERROR <> 0
			RETURN -1 --ERROR CREATING USER
		ELSE
			RETURN 1 --SUCCESS
	END
GO

CREATE PROCEDURE CREATE_DAILYGOAL
@USER_ID UNIQUEIDENTIFIER,
@EMOTION INT
AS
	BEGIN TRANSACTION
		INSERT DAILYGOAL VALUES(NEWID(), @USER_ID, GETDATE(), @EMOTION)
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1 --DAILY GOAL CREATION ERROR
			END
	COMMIT TRANSACTION
	RETURN 1 --SUCCESS
GO

CREATE PROCEDURE INSERT_SINGULAR_GOAL
@GOAL_ID INT,
@DAILY_GOAL_ID UNIQUEIDENTIFIER,
@GOAL_TEXT VARCHAR(50)
AS
	BEGIN
		INSERT GOAL VALUES(@GOAL_ID, @GOAL_TEXT, @DAILY_GOAL_ID)
		IF @@ERROR <> 0
			RETURN -1 --GOAL TEXT INSERTION ERROR
		ELSE
			RETURN 1 --SUCCESS
	END
GO

CREATE PROCEDURE CREATE_COMMENT
@USER_ID UNIQUEIDENTIFIER,
@COMMENT_MAIN VARCHAR(1000),
@COMMENT_EMOTION INT
AS
	BEGIN
		INSERT COMMENT VALUES(NEWID(), @USER_ID, @COMMENT_MAIN, GETDATE(), @COMMENT_EMOTION)
		IF @@ERROR <> 0
			RETURN -1 --COMMENT CREATION ERROR
		ELSE
			RETURN 1 --SUCCESS
	END
GO

-------------------------
--- UPDATE PROCEDURES ---
-------------------------

CREATE PROCEDURE MODIFY_USER
@USER_ID UNIQUEIDENTIFIER,
@USER_NAME VARCHAR(20),
@USER_MAIL VARCHAR(50)
AS
	BEGIN
		UPDATE USERS
		SET USER_NAME = @USER_NAME, USER_MAIL = @USER_MAIL
		WHERE USER_ID = @USER_ID
	END
GO

CREATE PROCEDURE MODIFY_GOAL_EMOTION
@DAILY_GOAL_ID UNIQUEIDENTIFIER,
@EMOTION INT
AS
	BEGIN
		UPDATE DAILYGOAL
		SET EMOTION = @EMOTION
		WHERE DAILY_GOAL_ID = @DAILY_GOAL_ID

		IF @@ERROR <> 0
			RETURN -1 --MODIFY ERROR
		ELSE
			RETURN 1 --SUCCESS
	END
GO

CREATE PROCEDURE MODIFY_GOAL_CONTENT
@DAILY_GOAL_ID UNIQUEIDENTIFIER,
@GOAL_TEXT VARCHAR(50)
AS
	BEGIN
		UPDATE GOAL
		SET	GOAL_TEXT = @GOAL_TEXT
		WHERE DAILY_GOAL_ID = @DAILY_GOAL_ID
		
		IF @@ERROR <> 0
			RETURN -1 --MODIFY ERROR
		ELSE
			RETURN 1 --SUCCESS
	END
GO

CREATE PROCEDURE MODIFY_COMMENT
@COMMENT_ID UNIQUEIDENTIFIER,
@COMMENT_MAIN VARCHAR(1000),
@COMMENT_EMOTION INT
AS
	BEGIN
		UPDATE COMMENT
		SET COMMENT_MAIN = @COMMENT_MAIN, COMMENT_EMOTION = @COMMENT_EMOTION, COMMENT_DATE = GETDATE()
		WHERE COMMENT_ID = @COMMENT_ID

		IF @@ERROR <> 0
			RETURN -1 --MODIFY ERROR
		ELSE
			RETURN 1 --SUCCESS
	END
GO

-------------------------
--- DELETE PROCEDURES ---
-------------------------

CREATE PROCEDURE DELETE_USER
@USER_ID UNIQUEIDENTIFIER
AS
	BEGIN TRANSACTION
		DELETE COMMENT WHERE USER_ID = @USER_ID
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1 --COMMENT'S DELETE ERROR
			END

		DELETE DAILYGOAL WHERE USER_ID = @USER_ID
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1 --DAILY GOAL'S DELETE ERROR
			END

		DELETE USERS WHERE USER_ID = @USER_ID
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1 --USER'S DELETE ERROR
			END
	COMMIT TRANSACTION
	RETURN 1 --SUCCESS
GO

CREATE PROCEDURE DELETE_DAILY_GOAL
@DAILY_GOAL_ID UNIQUEIDENTIFIER
AS
	BEGIN TRANSACTION
		DELETE GOAL WHERE DAILY_GOAL_ID = @DAILY_GOAL_ID
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1 --GOAL'S DELETE ERROR
			END
		
		DELETE DAILYGOAL WHERE DAILY_GOAL_ID = @DAILY_GOAL_ID
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1 --DAILY GOAL'S DELETE ERROR
			END

	COMMIT TRANSACTION
	RETURN 1 --SUCCESS
GO

CREATE PROCEDURE DELETE_COMMENT
@COMMENT_ID UNIQUEIDENTIFIER
AS
	BEGIN
		DELETE COMMENT WHERE COMMENT_ID = @COMMENT_ID
		IF @@ERROR <> 0
			RETURN -1 --COMMENT'S DELETE ERROR
		ELSE
			RETURN 1 --SUCCESS
	END
GO

-------------------------
---- READ PROCEDURES ----
-------------------------

CREATE PROCEDURE R_SINGLE_DAY_BY_ID
@DAILY_GOAL_ID UNIQUEIDENTIFIER
AS
	BEGIN
		SELECT * FROM DAILYGOAL D INNER JOIN GOAL G ON D.DAILY_GOAL_ID = G.DAILY_GOAL_ID
		WHERE D.DAILY_GOAL_ID = @DAILY_GOAL_ID
	END
GO

CREATE PROCEDURE R_7DAYS_BY_ID
@DAILY_GOAL_ID UNIQUEIDENTIFIER
AS
	BEGIN
		SELECT * FROM DAILYGOAL D INNER JOIN GOAL G ON D.DAILY_GOAL_ID = G.DAILY_GOAL_ID
		WHERE D.DAILY_GOAL_ID = @DAILY_GOAL_ID
		AND D.GOAL_DATE BETWEEN GETDATE() AND (GETDATE() - 7)
	END
GO

CREATE PROCEDURE R_42DAYS_BY_ID
@DAILY_GOAL_ID UNIQUEIDENTIFIER
AS
	BEGIN
		SELECT * FROM DAILYGOAL D INNER JOIN GOAL G ON D.DAILY_GOAL_ID = G.DAILY_GOAL_ID
		WHERE D.DAILY_GOAL_ID = @DAILY_GOAL_ID
		AND D.GOAL_DATE BETWEEN GETDATE() AND (GETDATE() - 42)
	END
GO

